### ISSUE TITLE
RESEARCH  AND OBJECTIVES REPORT: todo

### ISSUE THREAD

**Issue by obonobo** [atmos-sphere/atmos#1]
- [x] Introduction (JUSTIN - @JustinLohKingWei)
- [x] Hypothesis (ZUBAIR - @nuzurie)
- [x] Theoretical contribution (AMNEET - @amneet270)
- [x] Background/Related Work (AMINE - @instamine)
- [x] Methods (SEAN - @mckenzietsean)
- [x] Evaluation (ETHAN - @obonobo, AMINE - @instamine, ZUBAIR - @nuzurie)
- [ ] Biggest Risk

**Comment by obonobo** [comment]
## Methods

The stack we discussed so far looks like:
- React
- MaterialUI

Basically, it is just a social media web app
